#!/bin/sh
# PreToolUse(Write|Edit|MultiEdit): deny writes to secret files and generated code.
# Exit 2 = deny the tool call (stderr goes back to Claude as the reason);
# exit 1 = non-blocking warning shown to the user; exit 0 = allow.

command -v jq >/dev/null 2>&1 || {
  echo "guard-writes.sh: jq not found — secret/generated-file guard is NOT active" >&2
  exit 1
}

f=$(jq -r '.tool_input.file_path // empty' 2>/dev/null)
[ -n "$f" ] || exit 0

case "$f" in
  # Templates are fine.
  *.env.example) exit 0 ;;

  # Secrets / credentials — never through tooling.
  *.pem | */dev-keys/* | *.env | *.env.*)
    echo "Blocked: '$f' looks like a secret/credentials file. Edit it manually." >&2
    exit 2
    ;;

  # Generated code — the next codegen/build run silently overwrites hand edits.
  */ml/src/pina/ml/v1/*)
    echo "Blocked: '$f' is generated from proto/ ('make proto' in ml/). Edit the .proto source instead." >&2
    exit 2
    ;;
  */.react-router/*)
    echo "Blocked: '$f' is react-router typegen output (regenerated by typecheck/dev). Fix the route module instead." >&2
    exit 2
    ;;
  */backend/build/* | */frontend/build/* | */ml/.venv/*)
    echo "Blocked: '$f' is build output / vendored env. Edit the sources instead." >&2
    exit 2
    ;;
esac

exit 0
