import org.gradle.api.tasks.PathSensitivity

plugins {
    java
    jacoco
    id("io.quarkus")
    id("com.diffplug.spotless") version "8.8.0"
    id("com.github.spotbugs") version "6.5.10"
}

val quarkusPlatformVersion: String by project

repositories {
    mavenCentral()
}

dependencies {
    // Quarkus BOM
    implementation(enforcedPlatform("io.quarkus.platform:quarkus-bom:${quarkusPlatformVersion}"))

    // REST API
    implementation("io.quarkus:quarkus-rest")
    implementation("io.quarkus:quarkus-rest-jackson")
    implementation("io.quarkus:quarkus-hibernate-validator")

    // Database
    implementation("io.quarkus:quarkus-hibernate-orm-panache")
    implementation("io.quarkus:quarkus-jdbc-postgresql")
    implementation("io.quarkus:quarkus-flyway")
    implementation("jakarta.json.bind:jakarta.json.bind-api")
    // pgvector column mapping (photo embeddings / face descriptors)
    implementation("org.hibernate.orm:hibernate-vector")

    // OpenAPI
    implementation("io.quarkus:quarkus-smallrye-openapi")

    // Health checks
    implementation("io.quarkus:quarkus-smallrye-health")
    implementation("io.quarkus:quarkus-scheduler")

    // gRPC (backend↔ML contract; stubs generated from the shared ../proto dir)
    implementation("io.quarkus:quarkus-grpc")

    // Security & JWT
    implementation("io.quarkus:quarkus-smallrye-jwt")
    implementation("io.quarkus:quarkus-smallrye-jwt-build")
    implementation("at.favre.lib:bcrypt:0.10.2")

    // Configuration
    implementation("io.quarkus:quarkus-arc")
    implementation("com.github.ben-manes.caffeine:caffeine:3.2.4")

    // Image processing (thumbnailator for thumbnails, metadata-extractor for EXIF)
    implementation("net.coobird:thumbnailator:0.4.21")
    implementation("com.drewnoakes:metadata-extractor:2.20.0")

    // Testing
    testImplementation("io.quarkus:quarkus-junit5")
    testImplementation("io.quarkus:quarkus-junit5-mockito")
    testImplementation("io.quarkus:quarkus-jacoco")
    testImplementation("io.rest-assured:rest-assured")
    testImplementation("io.quarkus:quarkus-test-security")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

// gRPC code generation reads the shared contract instead of src/main/proto.
val sharedProtoDir = layout.projectDirectory.dir("../proto")

quarkus {
    quarkusBuildProperties.put("quarkus.grpc.codegen.proto-directory", sharedProtoDir.asFile.absolutePath)
}

tasks.withType<io.quarkus.gradle.tasks.QuarkusGenerateCode>().configureEach {
    inputs.dir(sharedProtoDir).withPathSensitivity(PathSensitivity.RELATIVE)
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-parameters")
}

tasks.withType<Test> {
    systemProperty("java.util.logging.manager", "org.jboss.logmanager.LogManager")
    // Pass-through for the proto golden fixture regeneration switch.
    systemProperty("pina.proto.golden.update", System.getProperty("pina.proto.golden.update", "false"))
}

val testStorageData = layout.buildDirectory.dir("test-data")

tasks.register<Delete>("cleanTestStorageData") {
    group = "verification"
    description = "Delete local storage artifacts generated by backend tests."
    delete(testStorageData)
}

// Code formatting
spotless {
    java {
        // Generated gRPC/protobuf sources are not subject to project formatting.
        targetExclude("build/**")
        eclipse()
        formatAnnotations()
        removeUnusedImports()
        importOrder()
        endWithNewline()
    }
}

// Static analysis
spotbugs {
    excludeFilter = file("spotbugs-exclude.xml")
}

tasks.withType<com.github.spotbugs.snom.SpotBugsTask> {
    reports.create("html") { required = true }
    reports.create("xml") { required = false }
}

// Trivy vulnerability scan (requires trivy on PATH: brew install trivy)
tasks.register<Exec>("trivy") {
    group = "verification"
    description = "Scan built JARs for HIGH/CRITICAL CVEs using Trivy"
    dependsOn("quarkusBuild")
    commandLine(
        "trivy", "rootfs", "build/quarkus-app",
        "--severity", "HIGH,CRITICAL",
        "--ignore-unfixed",
        "--exit-code", "1",
        "--scanners", "vuln",
        "--ignorefile", ".trivyignore"
    )
}

// Disable Gradle JaCoCo agent — quarkus-jacoco handles instrumentation
tasks.withType<Test> {
    doFirst {
        delete(testStorageData)
    }
    finalizedBy("cleanTestStorageData")
    extensions.configure<JacocoTaskExtension> {
        isEnabled = false
    }
}

// Coverage tasks (run explicitly, not part of build). They depend on test so a
// standalone invocation cannot report or verify against a stale exec file.
val quarkusExecData = layout.buildDirectory.file("jacoco/jacoco-quarkus.exec")

// Generated gRPC/protobuf classes are excluded from coverage accounting.
val jacocoClassExcludes = listOf("dev/pina/ml/v1/**")

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    executionData(quarkusExecData)
    classDirectories.setFrom(files(classDirectories.files.map { dir ->
        fileTree(dir) { exclude(jacocoClassExcludes) }
    }))
}

tasks.jacocoTestCoverageVerification {
    dependsOn(tasks.test)
    executionData(quarkusExecData)
    classDirectories.setFrom(files(classDirectories.files.map { dir ->
        fileTree(dir) { exclude(jacocoClassExcludes) }
    }))
    violationRules {
        rule {
            limit {
                counter = "INSTRUCTION"
                value = "COVEREDRATIO"
                minimum = "0.70".toBigDecimal()
            }
            limit {
                counter = "BRANCH"
                value = "COVEREDRATIO"
                minimum = "0.70".toBigDecimal()
            }
        }
    }
}
